excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

disabled_rules:
  - line_length
  - identifier_name
  - superfluous_disable_command
  - todo
  - cyclomatic_complexity
  - function_body_length
  - nesting
  - file_length
  - type_body_length
